server:
  port: 10002

spring:
  data:
    mongodb:
      database: rms-employees
      host: localhost
      port: 27017

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: true